import { StyleSheet, Platform } from 'react-native'

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  tabs: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    //alignItems: 'center',
    backgroundColor: '#4b5563',
    width: '100%',
    paddingVertical: 5,
    position: 'absolute',
    top: 0,
    zIndex: 1000,
  },
  tab: {
    color: '#f9fafb',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  activeTab: {
    borderBottomColor: '#60a5fa',
    fontWeight: 'bold',
  },
  content: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    fontSize: 16,
    color: '#3b82f6',
    backgroundColor: '#f9fafb',
  },
  activeContent: {
    display: 'flex',
  },
  historyNavigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
    marginBottom: 5,
  },
  programTitle: {
    fontSize: 20,
    color: '#1F2937',
    fontWeight: 'bold',
  },
  week: {
    marginBottom: 8,
    padding: 2,
    borderRadius: 8,
    backgroundColor: '#EEEEEE', 
  },
  day: {
    marginVertical: 6,
    padding: 2,
    borderRadius: 6,
    backgroundColor: '#E7E7E7', 
  },
  button: {
    backgroundColor: '#6B7280',
    color: '#fff',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
    fontSize: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3, // Adds shadow for Android
  },
  smallButton: {
    backgroundColor: '#6B7280',
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRadius: 6,
    marginHorizontal: 5,
    width: 90,
    alignItems: 'center',  
    justifyContent: 'center',     
  },
  largeButton: {
    backgroundColor: '#6B7280',
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRadius: 6,
    marginHorizontal: 5,
    width: 170,
    alignItems: 'center',  
    justifyContent: 'center',     
  },  
  buttonText: {
    fontSize: 14,
    color: '#FFFFFF',
}, 
  addButton: {
    backgroundColor: '#60a5fa',
    padding: 5,
    fontSize: 12,
    marginLeft: 10,
    borderRadius: 5,
  },
  exerciseList: {
    width: '100%',
    padding: 10,
    color: '#3b82f6',
  },
  exercise: {
    marginBottom: 15,
    padding: 15,
    borderRadius: 8,
    backgroundColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  setInput: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10, // Space between sets
    justifyContent: 'space-between',
  },
  setInputField: {
    width: 50,
    marginHorizontal: 10, // Adds space between inputs
    padding: 8,
    textAlign: 'center',
    borderColor: '#D1D5DB',
    borderWidth: 1,
    borderRadius: 6,
    color: '#374151',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
},
  overlay: {
    display: 'none',
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 5,
  },
  numericInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  incrementButton: {
      paddingHorizontal: 5,
      paddingVertical: 5,
      backgroundColor: '#BBBBBB',
      borderRadius: 4,
      width: 24,
  },
  incrementButtonText: {
      fontSize: 18,
      color: '#fff',
  },
  inputField: {
      width: 45,
      textAlign: 'center',
      marginHorizontal: 5,
      padding: 5,
      borderColor: '#d1d5db',
      borderWidth: 1,
      borderRadius: 4,
      color: '#374151',
  }, 
  infoTextContainer: {
    color: '#FFFFFF',
    textAlign: 'center',
    marginHorizontal: 5,
    padding: 5,
    flexDirection: 'row',
  },   
  boldText: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#1F2937',    
  },
  normalText: {
    fontWeight: 'normal',
    fontSize: 16,
    color: '#1F2937',    
  }
})