export const SETUP_USER = 'SETUP_USER'; // setups the user when using for the first time in the device
export const SET_DATA = 'SET_DATA'; // set initial data (from server)
export const SET_CURRENT_WORKOUT = 'SET_CURRENT_WORKOUT';
export const FINISH_CURRENT_WORKOUT = 'FINISH_CURRENT_WORKOUT'; // adds a workout to workout history (finish workout button)
export const DELETE_PAST_WORKOUT = 'DELETE_PAST_WORKOUT'; // deletes a workout from workout history
export const SET_CURRENT_PROGRAM = 'SET_CURRENT_PROGRAM'; // sets the current active program (create new or copy from a past program)
export const UPDATE_CURRENT_PROGRAM = 'UPDATE_CURRENT_PROGRAM'; // update the active program
export const ADD_PAST_PROGRAM = 'ADD_PAST_PROGRAM'; // add a program to the program history
export const DELETE_PAST_PROGRAM = 'DELETE_PAST_PROGRAM'; // deletes a past program from program history
export const REFRESH_AND_SET_DATA = 'REFRESH_AND_SET_DATA'; // refreshes data (read local and server data + merge)
export const ACTIVATE_PROGRAM = 'ACTIVATE_PROGRAM';
