services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
      MONGO_INITDB_DATABASE: gymtracker_db
    volumes:       
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js    
      - ./mongo_data:/data/db          
